QubesOS/qubes-gui-daemon

- gui-daemon/xside.c
When building the new main branch, there's error because the last null entry in **struct option longopts**  is not properly initialized.
```
make[1]: Entering directory `/home/user/qubes-src/gui-daemon/gui-daemon'
gcc -I../include/ -g -O2 -Wall -Wextra -Werror -pie -fPIC `pkg-config --cflags libconfig` `pkg-config --cflags libnotify` `pkg-config --cflags libpng` `pkg-config --cflags vchan-xen`   -c -o xside.o xside.c
xside.c:2614:2: error: missing initializer for field 'name' of 'struct option' [-Werror=missing-field-initializers]
{ },
^
In file included from xside.c:40:0:
/usr/include/getopt.h:106:15: note: 'name' declared here
const char *name;
^
cc1: all warnings being treated as errors
make[1]: *** [xside.o] Error 1
make[1]: Leaving directory …
```
> Fixed the error 'missing initializer' in struct option longopts (xside.c)

- screen-layout-handler/monitorlayoutnotify.py
When one output is disconnected, parsing "xrandr -q" will fail (for example line "VGA-0 disconnected"). This causes error message "Error starting VM <vm>: 'NoneType' object has no attribute 'groupdict'." when launching a VM.
The actual culprit is the required space after "(dis?)connected", but making everything after that optional solves the problem. Can be tested with following xrandr output:
```
Screen 0: minimum 320 x 200, current 3840 x 1200, maximum 16384 x 16384
HDMI-0 connected primary 1920x1200+0+0 518mm x 324mm
1920x1200     59.95*+
1920x1080     60.00
1600x1200     60.00
1680x1050     59.88
1280x1024     60.02
1440x900      59.90
1280x800      59.91
1280x720      60.00
1024x768      60.00
800x600       60.32
640x480       60.00
720x400       70.08
DVI-0 connected …
```
> Fix sending monitor layout info when xrandr has one output disconnected

- gui-daemon/xside.c
- gui-daemon/xside.h
- shmoverride/README
- shmoverride/shmoverride.c
This allows the gui daemon to be run without root privileges.
> Move /var/run/shm.id to /var/run/qubes/shm.id

- gui-daemon/qubes.ClipboardPaste.policy
Prior to commit 981a11ce in qubes-core-admin-linux, this was allowed
accidentally as a bug.
This manifested itself as the silent inability to paste into any AppVM
after clicking the "Copy to Qubes clipboard" button in the log viewer
of qubes-manager.
Writing the new clipboard data in dom0 would work fine, and you would
get a notification that the copy was successful, but the paste path
would cause is_special_keypress() to bail early without warning due to
evaluate_clipboard_policy() failing with source_vm = "dom0".
I did not detect this sooner because if qubes-clipboard.bin.source had
a trailing newline, then evaluate_clipboard_policy() would not fail,
and my dom0 clipboard-copyout script produced such a trailing newline.
> Allow copying out of dom0 at qrexec-policy level

- gui-daemon/xside.c
While compiling with clang, this error comes up because `g->vmname` will always be non-NULL, although it may not have been set properly and therefore its value might be empty.
```
xside.c:2933:13: error: address of array 'g->vmname' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
if (!g->vmname) {
~~~~^~~~~~
1 error generated.
<builtin>: recipe for target 'xside.o' failed
```
I have made a small fix for this: initializing the `g->vmname` char array with '\0' just before it is set, and making the change in the conditional to see it remains empty.
> Fix always true conditional

- gui-daemon/xside.c
Fix Gtk-Warning: `{Unknown tag "br" on line 1 char 365}` that causes the dialog to not be shown.
It looks like it doesn't handle the `\n`s very well either, but currently you get a blank pop-up with two options: `[Ignore]  [Terminate]` that keeps popping up again when you click `Ignore`, and where the VM gets stuck in `Transient` state forever and can't easily be repaired/killed/handled using the Xen tools if you click `Terminate`. This PR doesn't fix that, but at least it makes it easier to seek help if the user can see the error message.
> Fix Gtk-Warning: {Unknown tag "br" on line 1 char 365} 

- screen-layout-handler/qubes-screen-layout-watches.desktop
I don't believe this is the best long-term fix (having anything besides
the gui-daemon involved seems like more moving parts than necessary),
but it's the least intrusive change which produces the desired overall
behavior right now.
commit 25aa33cd3c6b5fc6a0689388a59fa9c7a720b95c
Author: Wojtek Porczyk <woju@invisiblethingslab.com>
Date:   Tue Mar 8 15:38:01 2016 +0100
Remove qubes-monitor-layout-notify
Was moved to core-admin.
is a lie. The script wasn't moved to core-admin... no such script exists
anymore. Instead, the code to get the AdminVM resolution and send it to
the guest VMs was integrated into qvm-start-gui in core-admin-client,
but only triggered on initial start of the VM and was never hooked up to
anything listening for randr events.
The fact that --all is required seems like …
> Actually dispatch resolution change notifications

- gui-daemon/xside.c
- gui-daemon/xside.h
Tested by setting a breakpoint in gdb before a VERIFY() and making the condition fail, rather than building a broken gui-agent. Worked as expected.
> Remove dependency on xl toolstack

- window-icon-updater/icon-receiver
Cache at most 5 icons received for windows not yet created at dom0 side.
If such window is detected later, apply a cached icon for it.
Fixes QubesOS/qubes-issues#1495
> icon-receiver: cache icons received for not (yet) existing windows

- shmoverride/README
The description sounds like a reasonable way to implement it, but it's apparently not how it's been implemented. I'm not sure why, but one theoretical reason might be to preemtively avoid potential bugs related to shmid recycling. For example, since X (allegedly) internally keeps track of shmids, if the temporary shmid matches one previously seen for a still-existing window, one might imagine bugs where the windows might end up with the same backing instead of X calling through to shmoverride.
In any case, this is confirmable by reading the code (look for `shmctl(..., IPC_RMID, ...)`), and by watching `/proc/sysvipc/shm`.
> Correct note about "temporary" shm lifecycle

- gui-daemon/xside.c
This sends the remote (the VM's) window id for `CLIPBOARD_DATA` events generated by `ctrl + shift + v`, like it is done with `CLIPBOARD_REQ` when you press `ctrl + shift +c`.
For Linux it does not make a big difference, since Xorg keeps track of which window currently has focused, but my implementation of the Qubes GUId protocol does not handle the concept of "focus" on a specific window, and it breaks my code that dispatches events to components based on window id.
This PR is interlinked with a PR to [qubes-gui-agent-linux](https://github.com/QubesOS/qubes-gui-agent-linux) because the Linux tooling currently ignores the length field and instead uses the window id field for transmitting the length, so it should not be merged without also merging my PR to that repository.
The Windows …
> CLIPBOARD_DATA: fix sending of window id when pasting to VMs

- pulse/pacat-simple-vchan.c
no effort is made on trying to detect/handle the "this looks more like a vm name than a domid" case.
the "danger" is no more than getting a valid numeric but still entirely wrong domid.
this seems acceptable for something thats more internal infrastructure than user facing tooling.
> allow domid 0 as target

- gui-daemon/trayicon.c
When only part of the icon was redrawn, the code used wrong coordinates
and instead of putting that part back at the correct (x, y) coordinates,
it put it at (x, x). Additionally, it used cropped part of that
icon, because of again using (x, x) start coordinates (in an image already
containing just updated fragment) instead of (0, 0).
It worked accidentally only when the application always redraw the whole
icon (or at least its top-left part - so x=y=0). Which apparently is a
very common thing applications do.
Fixes QubesOS/qubes-issues#5704
> Fix tray icon coloring code - do not crop/dislocate icon fragments

- gui-daemon/guid.conf
- gui-daemon/xside.c
- gui-daemon/xside.h
This pull request aims to mitigate/work around issue https://github.com/QubesOS/qubes-issues/issues/5731 by unsetting the override_redirect flag of windows that cover more than 90% of the screen. Please see the commit message for further information.
This commit was tested with Qubes OS 4.0 only. For Qubes OS 4.1, I have only verified that the code compiles as expected.
> xside: Introduce override_redirect protection

- debian/control
- debian/qubes-gui-daemon.install
- rpm_spec/gui-daemon.spec.in
- window-icon-updater/Makefile
- window-icon-updater/icon-receiver
- window-icon-updater/qubes-icon-receiver.desktop
- window-icon-updater/qubes.WindowIconUpdater
- window-icon-updater/qubes.WindowIconUpdater.config
As a result, we have a single service running for all the VMs.
Start it using /etc/xdg/autostart to ensure it's running in the
proper graphical session.
Depends on Image.get_from_stream_async, implemented in
QubesOS/qubes-linux-utils#52.
> Convert qubes.WindowIconUpdater to a socket service

- pulse/pacat-simple-vchan.c
- pulse/pacat-simple-vchan.h
1. Terminate when the target domain is killed
2. Create a pidfile (/var/run/qubes/pacat.<XID>) to prevent multiple instances.
The second one will only be effective with #35, as otherwise pacat-simple-vchan
is started as root (so the pidfile is unreadable for the normal user), but also
is killed with SIGTERM and does not cleanup the pid file.
Fixes QubesOS/qubes-issues#5760
> pulse: starting/stopping improvements

- Makefile.builder
Should be fixed by Marek's PR: https://github.com/QubesOS/qubes-gui-daemon/pull/26
> Currently disable failing builds for CentOS 7

- gui-daemon/xside.c
It is not necessary with xfwm, but is critical with Compiz because of event racing from decoration plugin and guest side.
> set override redirect attribute on window creating

- shmoverride/shmoverride.c
... for a cross-vm memory mapping. The fact that the shmctl was
intercepted by shmoverride, means the server should use the mapping. X
server checks if the shm region has sufficient access (for given
client) - since the check is already implicitly done by shmoverride,
announce 0666 mode and don't care about uid/gid.
Fixes QubesOS/qubes-issues#5896
> shmoverride: fill shm_perm when faking shmctl(IPC_STAT) output

- gui-daemon/guid.conf
- gui-daemon/xside.c
- gui-daemon/xside.h
Remove per-VM configuration, but allow providing a path to the
configuration file. This is in order to move GUI daemon
configuration to qvm-features.
(WIP until the other part of the change is done)
> Allow overriding configuration file

- gui-daemon/xside.c
- gui-daemon/xside.h
Detect a screensaver window by override_redirect, map state (an
inactive window is unmapped), and window class. Use XRestackWindows
to put newly appearing windows below such a window.
To test:
1. run in VM: while true; do notify-send "hey"; sleep 1; done
2. lock screen and check if notifications appear.
The problem doesn't seem to appear on i3lock. I haven't checked
KDE.
See QubesOS/qubes-issues#5908.
> Prevent VM notifications from appearing on top of xscreensaver

- window-icon-updater/icon-receiver
This adds an exception handler to the event loop, which will try to reestablish the xcb connection on error. The connection logic is pulled out of `IconReceiver.__init__` to a new `connect` method, to support this.
This does mitigate https://github.com/QubesOS/qubes-issues/issues/5979, but I hesitate to call it a complete fix. What happens for me is that `icon-receiver` still fails to connect for 6-7 seconds, during which time it's still spamming `.xsession-errors.old`, but it is eventually able to connect and the torrent of error logging stops.
> icon-receiver: Retry X connection on error

- gui-common/txrx-vchan.c
- gui-daemon/xside.c
When X server terminates (for example user logout), the X11 IO error
handler may be called, which terminates the process. Generally this is
fine, but gui-daemon has atexit(3) handler that tries to communicate
with X server (release_all_mapped_mfns() call). This operation fails
miserably (since X11 connection is broken) and in some cases makes the
process skip other atexit(3) handlers (if it crashes during some earlier
of them).  Especially it may cause skipping pidfile cleanup. Not
cleaning up the pidfile will prevent starting gui-daemon for this domain
after X server restart.
Fixes QubesOS/qubes-issues#6155
> Fix handling X11 exit

- gui-daemon/guid.conf
- gui-daemon/xside.c
- gui-daemon/xside.h
This adds two features:
- A flag to disable override redirect windows entirely.  This will break
many applications.
- A distance that any window must have from the top of the screen.  This
prevents an override redirect window from drawing over the taskbar
from the GUI domain.
> More protection vs override redirect windows

- gui-daemon/Makefile
There is random build issues when having encodings like RK1048. It
appears notably in reprotest.
Related issues:
- https://gitlab.com/QubesOS/qubes-gui-daemon/-/jobs/900656529#L808
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894217
> Enforce locale for help2man

- gui-daemon/xside.c
We use X11 event time to detect if any other clipboard operation
happened between user trigger (via key combo) and the actual operation
happens (like - VM sends the clipboard content). But when the X11 timer
wraps (every 2^32 ms = ~50 days), the check fails as the "clipboard
file" event time (just before the wrap) will be greater than the current
event time (just after the wrap).
Detect the wrap by checking if the difference is no larger than half of
the timer range.
Theoretically this could still fail if a single clipboard operation will
take ~25 days _and no other clipboard operation happens in the meantime_.
If another operation happens in the meantime, it _should_ fail.
Fixes QubesOS/qubes-issues#2189
> Fix clipboard stop working after ~50 days of uptime

- gui-daemon/qubes.ClipboardPaste.policy
- gui-daemon/xside.c
- gui-daemon/xside.h
- qubesguidaemon/mic.py
Outside of dom0, `qrexec-policy` is not available, but we can use
`qrexec-client-vm` and the `policy.EvalGUI` service instead.
Fixes QubesOS/qubes-issues#6263.
> Call policy.EvalSimple when outside of dom0

- gui-daemon/xside.c
They will not work properly, so just exit with a useful error message.
> Reject MSG_MFNDUMP outside of dom0

- debian/control
- gui-daemon/Makefile
- gui-daemon/xside.c
- gui-daemon/xside.h
- rpm_spec/gui-daemon.spec.in
This is necessary for all future XCB operations, and allows using XCB
instead of Xlib in the GUI daemon.  Complete conversion to XCB is not a
goal at this time, but XCB has several advantages over Xlib, so having
it be an option is desirable.
> Obtain an XCB connection handle

- gui-daemon/xside.c
- gui-daemon/xside.h
by setting the _NET_WM_USER_TIME property when needed.
Fixes QubesOS/qubes-issues#3727.
> Avoid rogue screen locking

- gui-daemon/xside.c
- gui-daemon/xside.h
Instead of trying to check for offscreen windows while sanitizing window
positions, return early in the case of offscreen windows, and then
sanitize x, y, width, height, x + width, and y + height separately.
This takes more code, but the new code is much, *much* simpler and
easier to understand.
Fixes QubesOS/qubes-issues#6518.
> force_on_screen(): fix calculations

- gui-daemon/xside.c
- include/list.h
There can be two types of relations:
- `parent`: in this case agent must destroy children windows first - if
that isn't the case, terminate abruptly
- `transient_for`: in that case clear the reference (both in local
structure and in the X server)
> Check if a window is referenced by another one before destroying it

- Makefile
Otherwise, builds would fail to pick up changes they really should.  In
the future, we should switch to non-recursive make to avoid this.
> Add missing .PHONY dependencies

- gui-daemon/Makefile
- shmoverride/Makefile
- shmoverride/shmoverride.c
This allows for more compiler optimizations and ensures that shmoverride
does not export more symbols than it should.
> Use -fvisibility=hidden for building C

- gui-daemon/xside.c
Marking as draft because I am not sure if the call to abort() is
justified.
Fixes QubesOS/qubes-issues#6518.
> Draft: Consider work area when positioning windows

- gui-daemon/xside.c
Force refreshing tray icon just after docking it
Fixes QubesOS/qubes-issues#6856
> Fix non-refreshed tray icons

- gui-common/txrx-vchan.c
- screen-layout-handler/watch-screen-layout-changes.c
since overflowing FD_SETSIZE is undefined behavior.
> Add FD_SETSIZE assertions

- gui-daemon/xside.c
An xfwm4 bug can cause the work area to temporarily be negative, causing
the GUI daemon to exit.  Ignore the invalid work area instead of
exiting.
Fixes QubesOS/qubes-issues#7309.
> Ignore bad work areas

- gui-daemon/Makefile
This helps ensure that the compiler won’t mess things up, and makes
memory corruption exploits more difficult.
> Add some hardening CFLAGS

- gui-daemon/guid.conf
- gui-daemon/xside.c
- gui-daemon/xside.h
The default GUI agent never creates them, and they are extra attack surface.  For instance, they are involved in one of the exploits for QSB#072.
> Disable subwindows by default

- gui-daemon/xside.c
- gui-daemon/xside.h
This allows bidirectional protocol negotiation, which means that the
agent can be newer than the daemon.
The daemon must be upgraded to support protocol 1.4 first.  Afterwards,
agents and daemons can be independently upgraded.
> Implement GUI protocol 1.4

- gui-daemon/xside.c
Hi @marmarek and @DemiMarie,
I believe that I have found the root cause of the "GUI-related lingering Xen grant references" issue reported in https://github.com/QubesOS/qubes-issues/issues/7539, and I prepared this patch to resolve it.
As noted in the commit message, I have only tested this with Qubes OS v4.1, but I do not see why this commit would not work on the master branch.
Thank you,
Vefa
> Release MFNs for unmapped windows as well

- gui-daemon/xside.c
That window is backing buffers of other windows too. Windows GUI agent
depends on this feature. The window itself is mapped/unmapped when
switching between seamless and fill desktop modes.
Fixes QubesOS/qubes-issues#7643
> xside: do not release buffer of the "whole screen" window

- gui-daemon/xside.c
This allows GUI agents to ignore messages sent to windows they have already destroyed.  Requires DemiMarie/qubes-gui-common@aad629400a873d7bc4b0f12c43843c9a08c2f13b.
Fixes QubesOS/qubes-issues#6914.
> Send MSG_DELETE_ID when destroying a window

- gui-daemon/xside.c
This was supposed to be done in 157ca1496ae0a6e578c124eb0c57217268d3ea3d, but the implementation was wrong: it set the override-redirect flag to what the GUI daemon thought the current value was, not 0.  Therefore, the GUI daemon could become confused as to the override-redirect state of a window.
This turns out not to be exploitable in practice unless subwindows are enabled.  With subwindows disabled, it is not possible to prevent the window from being marked as docked, which prevents moving, resizing, or mapping the window.  Since the window cannot be mapped by the VM, it cannot appear on screen unless the embedder tells the GUI daemon to map it.  The embedder will resize the window before sending this message, so there is no window of vulnerability.
Fixes: …
> Actually unset override-redirect when docking

- gui-daemon/xside.c
Otherwise (as it was previously, with the entirety of the message in the summary), some window managers, such as XFCE, will not wrap the notification correctly.
fixes QubesOS/qubes-issues#7312
> Fix notification to comply with summary/body format

- rpm_spec/gui-daemon.spec.in
pacat-simple-vchan works with PipeWire's PulseAudio server, not just
with PulseAudio itself.  Depend on the pulseaudio-daemon feature, which
is provided by both pipewire-pulesaudio and pulseaudio.
> Support pipewire-pulseaudio as well as pulseaudio

- gui-common/double-buffer.c
- gui-common/error.c
- gui-common/txrx-vchan.c
- gui-daemon/Makefile
- gui-daemon/png.c
- gui-daemon/trayicon.c
- gui-daemon/xside.c
- include/txrx.h
This fixes function prototype mismatches (caught using
-Wmissing-prototypes) and replaces select(2) with poll(2).  No change in
behavior.
> Fix function prototype mismatches and use poll(2)

- .gitlab-ci.yml
- pulse/pacat-simple-vchan.c
- pulse/pacat-simple-vchan.h
- rpm_spec/gui-daemon.spec.in
With pulseaudio socket activation, pulseaudio agent may not be running 
initially. This would be fine generally, as pacat-simple-vchan waits for 
the other end to start first, but it prevents attaching a microphone to the
VM before starting audio-recording app. Fix this by using async vchan
connection, and setup control socket early. Then connect to the actual
pulseaudio daemon (and setup audio streams) only when vchan connection get
established.
Fixes QubesOS/qubes-issues#7964
Depends on https://github.com/QubesOS/qubes-core-vchan-xen/pull/31
> Deal with delayed pulseaudio agent startup

- gui-daemon/xside.c
Negative width or height makes no sense.  Treat this as an error condition.  This allows simplifying the rest of do_shm_update(), as this corner case no longer needs to be checked for.
> do_shm_update: Negative width or height is an error

- gui-daemon/xside.c
The future Wayland agent will include a proxy for the X11 agent.  This proxy will rely on the `untrusted_len` field for message framing.  If the value in this field does not match the number of bytes the GUI daemon actually reads, chaos will ensue.
To catch this problem before it can create havoc, validate that the `untrusted_len` field of incoming messages is correct.  Furthermore, any validation error that happens before all input has been read is now fatal, as continuing would leave data in the input stream that would be parsed as future protocol messages.  Therefore, do not use `VERIFY()`, which asks the user if they wish to continue.  Instead, log a fatal error and exit.
> Strictly validate message lengths

- pulse/pacat-simple-vchan.c
- pulse/pacat-simple-vchan.h
This ensures that there is no data remaining in the playback vchan. Otherwise, this data would be played when the VM _next_ starts playing audio, which is clearly wrong.
Reported-by: Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>
Fixes: QubesOS/qubes-issues#8137
> Drain playback stream before corking it

- debian/control
- gui-daemon/Makefile
- gui-daemon/xside.c
- rpm_spec/gui-daemon.spec.in
This allows periods in qube names by using the function from libqubes-pure to validate them instead of the built-in version.
Part of QubesOS/qubes-issues#8199.
> Allow periods in qube names

- pulse/pacat-simple-vchan.c
- pulse/pacat-simple-vchan.h
This significantly improves audio quality compared to nonblocking mode. I believe this is because the PipeWire agent will usually be able to free up space in the capture vchan quickly enough to avoid an overrun.
This has not been tested directly, but it is equivalent to always passing -b as a command-line argument, which I did test.
Fixes: QubesOS/qubes-issues#8887
> Always block on vchan I/O by default

- pulse/pacat-simple-vchan.c
Related to QubesOS/qubes-issues#8955
> audio: change "low latency" buffer parameters

- pulse/pacat-simple-vchan.c
- pulse/pacat-simple-vchan.h
https://github.com/QubesOS/qubes-issues/issues/8975
> pacat-simple-vchan: reconnect on vchan eof

- qubesguidaemon/mic.py
after QubesOS/qubes-core-admin/pull/579
and after https://github.com/QubesOS/qubes-core-admin-client/pull/274
https://github.com/QubesOS/qubes-issues/issues/4626
> new device API

- Makefile
- rpm_spec/gui-daemon.spec.in
- selinux/qubes-gui-daemon.fc
- selinux/qubes-gui-daemon.te
This adds just enough for sys-gui-vnc to work, specifically to allow X
server access to /run/qubes/shm.id.0.
The actual GUI daemon remains unconfined at this time.
QubesOS/qubes-issues#9276
> Add basic SELinux policy

- gui-daemon/guid.conf
- gui-daemon/xside.c
- gui-daemon/xside.h
Note: in QubesOS/qubes-issues#9304 I wrote:
> My instinct is that an option of black or white is good enough; allowing the color to be an arbitrary hue perhaps grants this issue more attention than it deserves. Also, the implementation is simpler. But I defer to others.
I changed my mind about this in the meantime, I like dark blue, and in this change I allow the setting to be an arbitrary user-selected color. This obligates some error checking around `strtoul` and `XAllocNamedColor`. (An input sanitizing step upstream in memory-safe `qvm-features` -- QubesOS/qubes-issues#7730 -- would be a good complement.) If the user-selected color is invalid, `qubes-guid` bails with an error logged to `/var/log/qubes/guid.<vm>.log`.
I think this is ok? But let me know.
Fixes QubesOS/qubes-issues#9304
> Add window_background_color config setting

- .gitlab-ci.yml
- Makefile
- debian/qubes-audio-daemon.install
- pulse/pacat-simple-vchan.c
- pulse/pacat-simple-vchan.h
- pulse/qubes.AudioInputDisable
- pulse/qubes.AudioInputEnable
- qubesguidaemon/mic.py
- rpm_spec/gui-daemon.spec.in
- window-icon-updater/Makefile
Integration tests: https://github.com/QubesOS/qubes-core-admin/pull/608
> Use QubesDB for knowing if mic is allowed or not

- shmoverride/shmoverride.c
After I have rebased my qubesos nixos dom0 on latest nixos version, I have encountered Xwayland/Xorg failing with segfault.
The cause of segfault was fstat hook being called before library constructor:
This was not caused by constructor not finding fstat with dlsym, I have checked that no logs being emitted by this library (and double-checked by using bpftrace to catch all fprints to stderr), constructor defenitely was not being called.
I'm not sure why, but `-z initfirst` linker flag fixes this constructor call ordering issue, making constructor being run before fsync, thus fixing the segfault, and restoring the Xwayland/Xorg operation.
I can provide more info/logs about this issue, but my knowledge about dynamic linking is limited, and I have no idea what might be useful here.
> Fix: make shmoverride.so initfirst

- Makefile
- debian/qubes-gui-daemon.install
- rpm_spec/gui-daemon.spec.in
- shmoverride/.gitignore
- shmoverride/Makefile
- shmoverride/Xwayland-wrapper.in
- shmoverride/shmoverride.c
This is initial version that uses a wrapper. Draft PR, as alternative solution may be better (add env variable controlling which process to handle).
QubesOS/qubes-issues#8515
> Add support for loading shmoverride into Xwayland too

- .gitlab-ci.yml
- gui-daemon/guid.conf
- gui-daemon/xside.c
- gui-daemon/xside.h
1st part of fix. Making the clipboard buffer size configurable via `max_clipboard_size` setting within `guid.conf`
fixes: https://github.com/QubesOS/qubes-issues/issues/9296
> Make maximum clipboard buffer lenght configurable

- qubesguidaemon/mic.py
implements QubesOS/qubes-issues/issues/9325
> device identity

- gui-common/txrx-vchan.c
- gui-daemon/guid.conf
- gui-daemon/xside.c
- gui-daemon/xside.h
- include/txrx.h
Implement the functionality of [kloak](https://github.com/Whonix/kloak) (a tool designed to hide biometric behavior patterns in keystrokes and mouse movements) in qubes-gui-daemon. This PR will implement the functionality requested in https://github.com/QubesOS/qubes-issues/issues/1850 and fleshed out further in https://github.com/QubesOS/qubes-issues/issues/8541. It will also close https://github.com/QubesOS/qubes-issues/issues/8534 as it will no longer be necessary.
* Test rigorously on Qubes R4.3 (an earlier iteration of the code has been smoke-tested on Qubes R4.2, this hasn't been tested at all on R4.3 yet)
* Figure out why the domU window occasionally freezes until another input event is sent - we aren't buffering info coming from domU to dom0 so why this is happening is a mystery …
> Add event buffering for cloaking user input patterns

- window-icon-updater/icon-receiver
- Update `guivm-gui-agent` to `guivm`
- When the `icon-reciever` running on guivm other than dom0 the header received is as follow:
Request coming from appvm to dom0
```
service vm-name keyword adminvm\x00
```
Request coming from appvm to guivm
```
service vm-name\x00
```
The trailing `\x00` cause a bug when trying to get the color of the vm using `qubesadminapi`.
> Fix bugs in the icon-receiver

- gui-daemon/xside.c
resolves: https://github.com/QubesOS/qubes-issues/issues/9564
> Handle `disable` & `none` for secure copy/paste

- gui-daemon/xside.c
- gui-daemon/xside.h
resolves: https://github.com/QubesOS/qubes-issues/issues/6950
> Add `_NET_WM_PING` support

- gui-daemon/Makefile
- pulse/Makefile
Different distributions have different policy about this flag, avoid
setting it here to not conflict with distribution value.
Kinda related to QubesOS/qubes-issues#9597
> Leave defining _FORTIFY_SOURCE to distribution policy

- pulse/pacat-simple-vchan.c
- pulse/pacat-simple-vchan.h
After getting an event of QubesDB FD, actually call qdb_read_watch() so
the event is cleared and the next one can be received.
QubesOS/qubes-issues#9619
> audio: fix reacting on mic enable/disable requests

- gui-daemon/xside.c
fixes: https://github.com/QubesOS/qubes-issues/issues/9844
> Fix clipboard paste metadata for qrexec (Windows)

- gui-daemon/xside.c
Agent side should have replaced the end of very long window titles to
U+2026 (Horizontal Ellipsis). But the Daemon side might have been
configured to disallow UTF8 characters. Replace that character with ...
Supplements: https://github.com/QubesOS/qubes-gui-agent-linux/pull/227
Main issue: https://github.com/QubesOS/qubes-issues/issues/5986
> Replace U+2026 with ... if utf8 is disabled

- .gitignore
- gui-daemon/xside.c
The problem and solution is reported by `vx-sec` on  Github. It was found on Xmonad WM. The fix simply raises the override-redirect window to top, flushes display events and the restack windows for "Keep-on-top" windows to work properly
Also tested on the default XFCE on r4.3
resolves: https://github.com/QubesOS/qubes-issues/issues/9935
> Assure Popup Windows (override-redirect) open over parent

- pulse/pacat-simple-vchan.c
- pulse/pacat-simple-vchan.h
This makes streams list in pulseaudio/pipewire less cluttered (no
streams that wouldn't really record), but also fixes recording
indicator in xfce (which looks at connected streams, regardless of their
corked state).
More details in the commit message.
This requires a bit more testing, and also updating automated tests (they do assume currently the recording stream is always there).
And also some extra review would be nice.
Fixes QubesOS/qubes-issues#9999
> pulse: connect recording stream only when recording is allowed

- gui-daemon/xside.c
resolves: https://github.com/QubesOS/qubes-issues/issues/9978
> Notify users on clipboard paste denied by policies

- debian/control
Follow-up to #111 which did the same for Fedora.
Resolves https://github.com/QubesOS/qubes-issues/issues/9464.
> debian: Support pipewire-pulseaudio as well as pulseaudio

- debian/control
- debian/rules
- rpm_spec/gui-daemon.spec.in
> rpm: pull in notification proxy together with gui daemon

- window-icon-updater/icon-receiver
Python 3.14 (in Fedora 43) throws RunetimeError if event loop is not initialized before using it.
Resolves: QubesOS/qubes-issues#10188
> Initialize asyncio event loop before using it
