gui-daemon/xside.c

Use table instead of strcmp chain for modifier parsing

---

pulse/org.qubesos.Audio.conf
pulse/pacat-control-api.xml
pulse/pacat-control-object.c
qubesguidaemon/mic.py
rpm_spec/gui-dom0.spec
setup.py

This is very simple extension - only one device of the class exists and can be attached/detached.
Fixes QubesOS/qubes-issues#2941

Microphone device class

---

screen-layout-handler/watch-screen-layout-changes.c

Various improvements for watch-screen-layout-changes

---

gui-daemon/guid.conf

Per this issue: https://github.com/QubesOS/qubes-issues/issues/4573
Add explanatory text and better comments.

Add examples/comments to guid.conf

---

shmoverride/shmoverride.c

Instead of opening with O_CREAT|O_EXCL, use flock() to see if
the file is held by an alive Xorg process.
See 0ac0c7fcee1dcbc6235718b1b1fcf90131811973 for more context.
Solves part of QubesOS/qubes-issues#5273 (qubes-guid failing to
start after Xorg crash).

shmoverride: handle Xorg crash leaving shm.id file

---

gui-daemon/xside.c
gui-daemon/xside.h

See QubesOS/qubes-issues#1551.

Support MSG_CURSOR

---

pulse/pacat-simple-vchan.c

fix audio recording issue

---

qubesguidaemon/mic.py

It is deprecated and will be removed in Python 3.10.

Remove @asyncio.coroutine

---

Makefile
gui-daemon/xside.c
gui-daemon/xside.h
include/util.h

This should make some operations a little bit faster.

Move XInternAtom calls to startup

---

shmoverride/shmoverride.c

Avoid dangerous functions in shmoverride

---

.gitignore
Makefile
gui-daemon/Makefile
shmoverride/Makefile

This significantly improves the build system:
- Header dependencies are properly tracked
- Fewer calls to pkg-config
- Less code

Better build system

---

gui-daemon/xside.c

Related to QubesOS/qubes-issues#6518

Fix discovering desktop work area

---

gui-daemon/xside.c

See individual commit messages for details

Misc fixes

---

gui-daemon/xside.c

- replace tabs with spaces
- static_assert that MAX_GRANT_REFS_COUNT is not too high
- replace an assert with a static_assert

Miscellaneous cleanups; no change in behavior

---

gui-daemon/xside.c

This code is incredibly tricky and difficult to understand.  It turns
out to be correct, but checking that took hours, so add some comments to
help anyone else who looks at it.

Add comments in do_shm_update

---

Makefile

Small typo in the help of the Makefile

Typo in the help of the Makefile

---

gui-daemon/xside.c

This does not solve QubesOS/qubes-issues#7309, but it will help find the
cause of that problem.

Log invalid desktop or work area before exiting

---

pulse/Makefile
pulse/pacat-simple-vchan.c
pulse/pacat-simple-vchan.h

This fixes multiple bugs in pacat-simple-vchan.  See individual commit messages for details.

Fix pacat-simple-vchan

---

gui-daemon/xside.c
gui-daemon/xside.h

do_shm_update is an extremely tricky function, with lots of potential
for bugs.  Add assertions and comments to explain why it is in fact
correct.

Add assertions and comments in do_shm_update

---

Makefile
pulse/Makefile

This slightly improves the build system.

Make the build system a bit better

---

gui-daemon/xside.c

See individual commit messages for details.

Stricter command line parsing

---

gui-daemon/xside.c

Add do-while loops and ensure that min() and max() only evaluate their
arguments once.

Clean up some macros

---

Makefile
common/90-default-gui-daemon.policy
debian/not-installed
debian/qubes-gui-daemon.install
rpm_spec/gui-daemon.spec.in
window-icon-updater/Makefile

- fix installation order, to make files owned by the qubes group
- convert policy to the new format

Fixes for R4.2

---

gui-daemon/xside.c

This should never happen, but due to a bug in XFWM4 it can happen. Instead of crashing, log the problem and use the old values.
Fixes: QubesOS/qubes-issues#8824

Do not crash if the work area is invalid

---

gui-daemon/xside.c

See individual commit messages for details.  No change in behavior.

Minor cleanups

---

gui-daemon/xside.c
gui-daemon/xside.h

resolves: https://github.com/QubesOS/qubes-issues/issues/9571

Add `_NET_WM_NAME` & `_NET_WM_ICON_NAME` support
